# Google Cloud Build configuration for WorkflowGuard
steps:
  # Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/workflowguard-backend:$BUILD_ID', './backend']
    id: 'build-backend'

  # Build Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/workflowguard-frontend:$BUILD_ID', './frontend']
    id: 'build-frontend'

  # Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/workflowguard-backend:$BUILD_ID']
    id: 'push-backend'
    waitFor: ['build-backend']

  # Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/workflowguard-frontend:$BUILD_ID']
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # Deploy Backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'workflowguard-backend'
      - '--image=gcr.io/$PROJECT_ID/workflowguard-backend:$BUILD_ID'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=4000'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--set-env-vars=NODE_ENV=production'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # Deploy Frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'workflowguard-frontend'
      - '--image=gcr.io/$PROJECT_ID/workflowguard-frontend:$BUILD_ID'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=80'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=10'
    id: 'deploy-frontend'
    waitFor: ['push-frontend']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'
