# Google Cloud Build configuration for WorkflowGuard
# This file defines how to build and deploy both frontend and backend services

steps:
  # Minimal test - just build and push one image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/continual-mind-473007-h8/workflowguard-containers/workflowguard-backend:$BUILD_ID', './backend']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/continual-mind-473007-h8/workflowguard-containers/workflowguard-backend:$BUILD_ID']

  # Build TypeScript frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', './frontend/Dockerfile.production', '-t', 'us-central1-docker.pkg.dev/continual-mind-473007-h8/workflowguard-containers/workflowguard-frontend:$BUILD_ID', './frontend']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/continual-mind-473007-h8/workflowguard-containers/workflowguard-frontend:$BUILD_ID']

  # Deploy backend with proper secret configuration
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'workflowguard-backend'
      - '--image=us-central1-docker.pkg.dev/continual-mind-473007-h8/workflowguard-containers/workflowguard-backend:$BUILD_ID'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=4000'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--max-instances=5'
      - '--concurrency=80'
      - '--timeout=900'
      - '--set-env-vars=NODE_ENV=production'
      - '--set-secrets=DATABASE_URL=DATABASE_URL:latest'
      - '--set-secrets=DIRECT_URL=DIRECT_URL:latest'
      - '--set-secrets=JWT_SECRET=JWT_SECRET:latest'
      - '--set-secrets=HUBSPOT_CLIENT_ID=HUBSPOT_CLIENT_ID:latest'
      - '--set-secrets=HUBSPOT_CLIENT_SECRET=HUBSPOT_CLIENT_SECRET:latest'
      - '--set-secrets=HUBSPOT_REDIRECT_URI=HUBSPOT_REDIRECT_URI:latest'
      - '--set-secrets=RAZORPAY_KEY_ID=RAZORPAY_KEY_ID:latest'
      - '--set-secrets=RAZORPAY_KEY_SECRET=RAZORPAY_KEY_SECRET:latest'
      - '--set-env-vars=RAZORPAY_WEBHOOK_SECRET=Liverpoolisthebest@1998'
      - '--set-env-vars=RAZORPAY_PLAN_ID_STARTER_INR=plan_R6RI02CsUCUlDz'
      - '--set-env-vars=RAZORPAY_PLAN_ID_PROFESSIONAL_INR=plan_R6RKEg5mqJK6Ky'
      - '--set-env-vars=RAZORPAY_PLAN_ID_ENTERPRISE_INR=plan_R6RKnjqXu0BZsH'
      - '--set-env-vars=RAZORPAY_PLAN_ID_STARTER_USD=plan_RBDqWapKHZfPU7'
      - '--set-env-vars=RAZORPAY_PLAN_ID_PROFESSIONAL_USD=plan_RBDrKWI81HS1FZ'
      - '--set-env-vars=RAZORPAY_PLAN_ID_ENTERPRISE_USD=plan_RBDrX9dGapWrTe'
      - '--set-env-vars=RAZORPAY_PLAN_ID_STARTER_GBP=plan_RBFxk81S3ySXxj'
      - '--set-env-vars=RAZORPAY_PLAN_ID_PROFESSIONAL_GBP=plan_RBFy8LsuW36jIj'
      - '--set-env-vars=RAZORPAY_PLAN_ID_ENTERPRISE_GBP=plan_RBFyJlB5jxwxB9'
      - '--set-env-vars=RAZORPAY_PLAN_ID_STARTER_EUR=plan_RBFjbYhAtD3snL'
      - '--set-env-vars=RAZORPAY_PLAN_ID_PROFESSIONAL_EUR=plan_RBFjqo5wE0d4jz'
      - '--set-env-vars=RAZORPAY_PLAN_ID_ENTERPRISE_EUR=plan_RBFovOUIUXISBE'
      - '--set-env-vars=RAZORPAY_PLAN_ID_STARTER_CAD=plan_RBFrtufmxmxwi8'
      - '--set-env-vars=RAZORPAY_PLAN_ID_PROFESSIONAL_CAD=plan_RBFsD6U2rQb4B6'
      - '--set-env-vars=RAZORPAY_PLAN_ID_ENTERPRISE_CAD=plan_RBFscXaosRIzEc'

  # Deploy frontend service
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'workflowguard-frontend'
      - '--image=us-central1-docker.pkg.dev/continual-mind-473007-h8/workflowguard-containers/workflowguard-frontend:$BUILD_ID'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=80'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=3'
      - '--concurrency=80'
      - '--set-env-vars=NODE_ENV=production'
      - '--set-env-vars=VITE_API_URL=https://api.workflowguard.pro'
      - '--set-env-vars=VITE_APP_URL=https://www.workflowguard.pro'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  
# Build timeout (30 minutes)
timeout: 1800s