# Google Cloud Build configuration for WorkflowGuard
steps:
  # Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/continual-mind-473007-h8/workflowguard-containers/workflowguard-backend:$BUILD_ID', './backend']
    id: 'build-backend'

  # Build Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/continual-mind-473007-h8/workflowguard-containers/workflowguard-frontend:$BUILD_ID', './frontend']
    id: 'build-frontend'

  # Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/continual-mind-473007-h8/workflowguard-containers/workflowguard-backend:$BUILD_ID']
    id: 'push-backend'
    waitFor: ['build-backend']

  # Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/continual-mind-473007-h8/workflowguard-containers/workflowguard-frontend:$BUILD_ID']
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # Deploy Backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'workflowguard-backend'
      - '--image=us-central1-docker.pkg.dev/continual-mind-473007-h8/workflowguard-containers/workflowguard-backend:$BUILD_ID'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=4000'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--set-env-vars=NODE_ENV=production'
      - '--env-vars-file=.env.backend'
      - '--set-env-vars=DATABASE_URL=postgresql://postgres:postgres123@db:5432/workflowguard'
      - '--set-env-vars=HUBSPOT_CLIENT_ID=5e6a6429-8317-4e2a-a9b5-46e8669f72f6'
      - '--set-env-vars=HUBSPOT_CLIENT_SECRET=07f931e2-bc75-4686-a9cf-c1d464c55019'
      - '--set-env-vars=JWT_SECRET=xrDmUc9gji+BcWHxH2gEPhjvNDDehJDs4Z04UI/bVn1fhjmKOgH9WoUUnrVEFYcaTlYmbUdhaoSysZWHiNy5Dw=='
      - '--set-env-vars=RAZORPAY_KEY_ID=rzp_live_R6PjXR1FYupO0Y'
      - '--set-env-vars=RAZORPAY_KEY_SECRET=O5McpwbAgoiSNMJDQetruaTK'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # Deploy Frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'workflowguard-frontend'
      - '--image=us-central1-docker.pkg.dev/continual-mind-473007-h8/workflowguard-containers/workflowguard-frontend:$BUILD_ID'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=80'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--env-vars-file=.env.frontend'
      - '--set-env-vars=VITE_API_URL=https://workflowguard.pro'
    id: 'deploy-frontend'
    waitFor: ['push-frontend']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'
