# Google Cloud Build configuration for WorkflowGuard
# Service Account: workflowguard-build@$PROJECT_ID.iam.gserviceaccount.com
steps:
  # Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/continual-mind-473007-h8/workflowguard-containers/workflowguard-backend:$BUILD_ID', './backend']
    id: 'build-backend'

  # Build Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/continual-mind-473007-h8/workflowguard-containers/workflowguard-frontend:$BUILD_ID', './frontend']
    id: 'build-frontend'

  # Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/continual-mind-473007-h8/workflowguard-containers/workflowguard-backend:$BUILD_ID']
    id: 'push-backend'
    waitFor: ['build-backend']

  # Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/continual-mind-473007-h8/workflowguard-containers/workflowguard-frontend:$BUILD_ID']
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # Deploy Backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'services'
      - 'update'
      - 'workflowguard-backend'
      - '--region=us-central1'
      - '--platform=managed'
      - '--image=us-central1-docker.pkg.dev/continual-mind-473007-h8/workflowguard-containers/workflowguard-backend:$BUILD_ID'
      - '--port=4000'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--timeout=600'
      - '--set-env-vars=DATABASE_URL=postgresql://neondb_owner:npg_oPpKhNtTR20d@ep-dry-resonance-afgqyybz-pooler.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require,DIRECT_URL=postgresql://neondb_owner:npg_oPpKhNtTR20d@ep-dry-resonance-afgqyybz.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require,NODE_ENV=production,HUBSPOT_CLIENT_ID=5e6a6429-8317-4e2a-a9b5-46e8669f72f6,HUBSPOT_CLIENT_SECRET=07f931e2-bc75-4686-a9cf-c1d464c55019,HUBSPOT_REDIRECT_URI=https://api.workflowguard.pro/api/auth/hubspot/callback,JWT_SECRET=xrDmUc9gji+BcWHxH2gEPhjvNDDehJDs4Z04UI/bVn1fhjmKOgH9WoUUnrVEFYcaTlYmbUdhaoSysZWHiNy5Dw==,RAZORPAY_KEY_ID=rzp_live_RP85gyDpAKJ4Au,RAZORPAY_KEY_SECRET=j7s5n6sJ4Yec4n3AdSYeJ2LW,RAZORPAY_WEBHOOK_SECRET=Liverpoolisthebest@1998,RAZORPAY_PLAN_ID_STARTER_INR=plan_R6RI02CsUCUlDz,RAZORPAY_PLAN_ID_PROFESSIONAL_INR=plan_R6RKEg5mqJK6Ky,RAZORPAY_PLAN_ID_ENTERPRISE_INR=plan_R6RKnjqXu0BZsH,RAZORPAY_PLAN_ID_STARTER_USD=plan_RBDqWapKHZfPU7,RAZORPAY_PLAN_ID_PROFESSIONAL_USD=plan_RBDrKWI81HS1FZ,RAZORPAY_PLAN_ID_ENTERPRISE_USD=plan_RBDrX9dGapWrTe,RAZORPAY_PLAN_ID_STARTER_GBP=plan_RBFxk81S3ySXxj,RAZORPAY_PLAN_ID_PROFESSIONAL_GBP=plan_RBFy8LsuW36jIj,RAZORPAY_PLAN_ID_ENTERPRISE_GBP=plan_RBFyJlB5jxwxB9,RAZORPAY_PLAN_ID_STARTER_EUR=plan_RBFjbYhAtD3snL,RAZORPAY_PLAN_ID_PROFESSIONAL_EUR=plan_RBFjqo5wE0d4jz,RAZORPAY_PLAN_ID_ENTERPRISE_EUR=plan_RBFovOUIUXISBE,RAZORPAY_PLAN_ID_STARTER_CAD=plan_RBFrtufmxmxwi8,RAZORPAY_PLAN_ID_PROFESSIONAL_CAD=plan_RBFsD6U2rQb4B6,RAZORPAY_PLAN_ID_ENTERPRISE_CAD=plan_RBFscXaosRIzEc,TWILIO_ACCOUNT_SID=ACbee0672c967962b2212e68bf188771d2,TWILIO_AUTH_TOKEN=b80c34629dd5c41c26355dc6d60bca88'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # Deploy Frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'services'
      - 'update'
      - 'workflowguard-frontend'
      - '--region=us-central1'
      - '--platform=managed'
      - '--image=us-central1-docker.pkg.dev/continual-mind-473007-h8/workflowguard-containers/workflowguard-frontend:$BUILD_ID'
      - '--port=80'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--set-env-vars=VITE_API_URL=https://api.workflowguard.pro,VITE_APP_URL=https://www.workflowguard.pro,NODE_ENV=production'
    id: 'deploy-frontend'
    waitFor: ['push-frontend']

options:
  logging: CLOUD_LOGGING_ONLY
  # Using default machine type to avoid quota restrictions

timeout: '1800s'