# Google Cloud Build configuration for WorkflowGuard
# This file defines how to build and deploy both frontend and backend services

steps:
  # Minimal test - just build and push one image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/continual-mind-473007-h8/workflowguard-containers/workflowguard-backend:$BUILD_ID', './backend']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/continual-mind-473007-h8/workflowguard-containers/workflowguard-backend:$BUILD_ID']

  # Build TypeScript frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', './frontend/Dockerfile.production', '-t', 'us-central1-docker.pkg.dev/continual-mind-473007-h8/workflowguard-containers/workflowguard-frontend:$BUILD_ID', './frontend']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/continual-mind-473007-h8/workflowguard-containers/workflowguard-frontend:$BUILD_ID']

  # Deploy backend with proper secret configuration
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'workflowguard-backend'
      - '--image=us-central1-docker.pkg.dev/continual-mind-473007-h8/workflowguard-containers/workflowguard-backend:$BUILD_ID'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=4000'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--max-instances=5'
      - '--concurrency=80'
      - '--timeout=900'
      - '--set-env-vars=NODE_ENV=production'
      - '--set-secrets=DATABASE_URL=DATABASE_URL:latest'
      - '--set-secrets=DIRECT_URL=DIRECT_URL:latest'
      - '--set-secrets=JWT_SECRET=JWT_SECRET:latest'
      - '--set-secrets=HUBSPOT_CLIENT_ID=HUBSPOT_CLIENT_ID:latest'
      - '--set-secrets=HUBSPOT_CLIENT_SECRET=HUBSPOT_CLIENT_SECRET:latest'
      - '--set-secrets=HUBSPOT_REDIRECT_URI=HUBSPOT_REDIRECT_URI:latest'
      - '--set-secrets=RAZORPAY_KEY_ID=RAZORPAY_KEY_ID:latest'
      - '--set-secrets=RAZORPAY_KEY_SECRET=RAZORPAY_KEY_SECRET:latest'

  # Deploy frontend service
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'workflowguard-frontend'
      - '--image=us-central1-docker.pkg.dev/continual-mind-473007-h8/workflowguard-containers/workflowguard-frontend:$BUILD_ID'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=80'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=3'
      - '--concurrency=80'
      - '--set-env-vars=NODE_ENV=production'
      - '--set-env-vars=VITE_API_URL=https://api.workflowguard.pro'
      - '--set-env-vars=VITE_APP_URL=https://www.workflowguard.pro'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  
# Build timeout (30 minutes)
timeout: 1800s