version: '3.8'

services:
  # Database
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: npg_oPpKhNtTR20d
      POSTGRES_DB: neondb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U neondb_owner -d neondb"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env.backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["sh", "-c", "npx prisma migrate deploy && npx prisma generate && npm run start:prod"]

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=https://workflowguard.pro
      - VITE_APP_URL=https://workflowguard.pro
      - NODE_ENV=production
    depends_on:
      - backend

volumes:
  postgres_data: