version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: workflowguard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DATABASE_URL: "postgresql://neondb_owner:npg_oPpKhNtTR20d@ep-dry-resonance-afgqyybz-pooler.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      DIRECT_URL: "postgresql://neondb_owner:npg_oPpKhNtTR20d@ep-dry-resonance-afgqyybz.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      PORT: 4000
      NODE_ENV: production
      HUBSPOT_APP_ID: "18270797"
      HUBSPOT_CLIENT_ID: "5e6a6429-8317-4e2a-a9b5-46e8669f72f6"
      HUBSPOT_CLIENT_SECRET: "07f931e2-bc75-4686-a9cf-c1d464c55019"
      HUBSPOT_REDIRECT_URI: "https://api.workflowguard.pro/api/auth/hubspot/callback"
      RAZORPAY_KEY_ID: "rzp_test_placeholder"
      RAZORPAY_KEY_SECRET: "placeholder_secret"
      RAZORPAY_WEBHOOK_SECRET: "placeholder_webhook"
      RAZORPAY_PLAN_ID_STARTER_INR: "plan_starter_placeholder"
      RAZORPAY_PLAN_ID_PROFESSIONAL_INR: "plan_professional_placeholder"
      RAZORPAY_PLAN_ID_ENTERPRISE_INR: "plan_enterprise_placeholder"
    expose:
      - "4000"
    depends_on:
      - db 

  frontend:
    build: ./frontend
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-ssl.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data: