apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: workflowguard-backend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/timeout: "600s"
    spec:
      containerConcurrency: 80
      containers:
      - image: us-central1-docker.pkg.dev/continual-mind-473007-h8/workflowguard-containers/workflowguard-backend:latest
        ports:
        - containerPort: 4000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "4000"
        - name: DATABASE_URL
          value: "postgresql://neondb_owner:npg_oPpKhNtTR20d@ep-dry-resonance-afgqyybz-pooler.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
        - name: DIRECT_URL
          value: "postgresql://neondb_owner:npg_oPpKhNtTR20d@ep-dry-resonance-afgqyybz.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
        - name: HUBSPOT_CLIENT_ID
          value: "5e6a6429-8317-4e2a-a9b5-46e8669f72f6"
        - name: HUBSPOT_CLIENT_SECRET
          value: "07f931e2-bc75-4686-a9cf-c1d464c55019"
        - name: HUBSPOT_REDIRECT_URI
          value: "https://api.workflowguard.pro/api/auth/hubspot/callback"
        - name: JWT_SECRET
          value: "xrDmUc9gji+BcWHxH2gEPhjvNDDehJDs4Z04UI/bVn1fhjmKOgH9WoUUnrVEFYcaTlYmbUdhaoSysZWHiNy5Dw=="
        - name: RAZORPAY_KEY_ID
          value: "rzp_live_RP85gyDpAKJ4Au"
        - name: RAZORPAY_KEY_SECRET
          value: "j7s5n6sJ4Yec4n3AdSYeJ2LW"
        - name: RAZORPAY_WEBHOOK_SECRET
          value: "Liverpoolisthebest@1998"
        - name: RAZORPAY_PLAN_ID_STARTER_INR
          value: "plan_R6RI02CsUCUlDz"
        - name: RAZORPAY_PLAN_ID_PROFESSIONAL_INR
          value: "plan_R6RKEg5mqJK6Ky"
        - name: RAZORPAY_PLAN_ID_ENTERPRISE_INR
          value: "plan_R6RKnjqXu0BZsH"
        - name: TWILIO_ACCOUNT_SID
          value: "ACbee0672c967962b2212e68bf188771d2"
        - name: TWILIO_AUTH_TOKEN
          value: "b80c34629dd5c41c26355dc6d60bca88"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
