services:
  - type: web
    name: workflowguard-backend
    env: node
    runtime: node
    nodeVersion: 20
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_oPpKhNtTR20d@ep-dry-resonance-afgqyybz-pooler.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: DIRECT_URL
        value: postgresql://neondb_owner:npg_oPpKhNtTR20d@ep-dry-resonance-afgqyybz-pooler.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: JWT_SECRET
        value: dDjMTsWdYi+VBy4J5+ocmBbazSM+NJgunjbgBggZPOu8HNzXoUijNXiRbvHZ7JWcFfkHDDEbdeYwzFb9HvqDMw==
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production
      - key: HUBSPOT_CLIENT_ID
        value: ""
      - key: HUBSPOT_CLIENT_SECRET
        value: ""
      - key: HUBSPOT_REDIRECT_URI
        value: https://api.workflowguard.pro/api/auth/hubspot/callback