declare const _default: (() => {
    clientId: string | undefined;
    clientSecret: string | undefined;
    redirectUri: string;
    frontendUrl: string;
    apiUrl: string;
    scopes: string;
    apiBaseUrl: string;
    apiTimeout: number;
    maxRetries: number;
    retryDelay: number;
    rateLimitPerMinute: number;
    rateLimitPerHour: number;
    rateLimitPerDay: number;
    tokenRefreshBuffer: number;
    maxTokenAge: number;
    maxWorkflowsPerRequest: number;
    workflowSyncInterval: number;
    workflowBackupInterval: number;
    maxConsecutiveFailures: number;
    failureBackoffMultiplier: number;
    maxBackoffDelay: number;
    logLevel: string;
    enableDetailedLogging: boolean;
    tokenEncryptionKey: string | undefined;
    enableTokenEncryption: boolean;
    enableHealthChecks: boolean;
    healthCheckInterval: number;
    connectionTimeout: number;
    webhookSecret: string | undefined;
    webhookTimeout: number;
    minimumPortalPlan: string;
    requiredFeatures: string[];
    maxWorkflowVersions: number;
    workflowVersionRetentionDays: number;
    auditLogRetentionDays: number;
    enableAutomaticBackups: boolean;
    backupSchedule: string;
    backupRetentionDays: number;
    enableFailureNotifications: boolean;
    notificationChannels: string[];
    criticalErrorThreshold: number;
    enableCaching: boolean;
    cacheTTL: number;
    maxConcurrentRequests: number;
    enableMockMode: boolean;
    mockDataPath: string | undefined;
    enableDataEncryption: boolean;
    enableAuditLogging: boolean;
    gdprCompliant: boolean;
    dataRetentionPolicy: string;
    maxUsersPerPortal: number;
    maxWorkflowsPerUser: number;
    maxApiCallsPerMinute: number;
    maxApiCallsPerHour: number;
    enableAutomaticRetry: boolean;
    maxRetryAttempts: number;
    retryStrategy: string;
    alertThresholds: {
        apiErrorRate: number;
        responseTime: number;
        tokenRefreshFailures: number;
        connectionFailures: number;
    };
    features: {
        enableWorkflowComparison: boolean;
        enableVersionHistory: boolean;
        enableAutomaticBackups: boolean;
        enableRealTimeSync: boolean;
        enableAdvancedAnalytics: boolean;
        enableAuditLogging: boolean;
        enableApiAccess: boolean;
    };
}) & import("@nestjs/config").ConfigFactoryKeyHost<{
    clientId: string | undefined;
    clientSecret: string | undefined;
    redirectUri: string;
    frontendUrl: string;
    apiUrl: string;
    scopes: string;
    apiBaseUrl: string;
    apiTimeout: number;
    maxRetries: number;
    retryDelay: number;
    rateLimitPerMinute: number;
    rateLimitPerHour: number;
    rateLimitPerDay: number;
    tokenRefreshBuffer: number;
    maxTokenAge: number;
    maxWorkflowsPerRequest: number;
    workflowSyncInterval: number;
    workflowBackupInterval: number;
    maxConsecutiveFailures: number;
    failureBackoffMultiplier: number;
    maxBackoffDelay: number;
    logLevel: string;
    enableDetailedLogging: boolean;
    tokenEncryptionKey: string | undefined;
    enableTokenEncryption: boolean;
    enableHealthChecks: boolean;
    healthCheckInterval: number;
    connectionTimeout: number;
    webhookSecret: string | undefined;
    webhookTimeout: number;
    minimumPortalPlan: string;
    requiredFeatures: string[];
    maxWorkflowVersions: number;
    workflowVersionRetentionDays: number;
    auditLogRetentionDays: number;
    enableAutomaticBackups: boolean;
    backupSchedule: string;
    backupRetentionDays: number;
    enableFailureNotifications: boolean;
    notificationChannels: string[];
    criticalErrorThreshold: number;
    enableCaching: boolean;
    cacheTTL: number;
    maxConcurrentRequests: number;
    enableMockMode: boolean;
    mockDataPath: string | undefined;
    enableDataEncryption: boolean;
    enableAuditLogging: boolean;
    gdprCompliant: boolean;
    dataRetentionPolicy: string;
    maxUsersPerPortal: number;
    maxWorkflowsPerUser: number;
    maxApiCallsPerMinute: number;
    maxApiCallsPerHour: number;
    enableAutomaticRetry: boolean;
    maxRetryAttempts: number;
    retryStrategy: string;
    alertThresholds: {
        apiErrorRate: number;
        responseTime: number;
        tokenRefreshFailures: number;
        connectionFailures: number;
    };
    features: {
        enableWorkflowComparison: boolean;
        enableVersionHistory: boolean;
        enableAutomaticBackups: boolean;
        enableRealTimeSync: boolean;
        enableAdvancedAnalytics: boolean;
        enableAuditLogging: boolean;
        enableApiAccess: boolean;
    };
}>;
export default _default;
