"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const config_1 = require("@nestjs/config");
exports.default = (0, config_1.registerAs)('hubspot', () => ({
    clientId: process.env.HUBSPOT_CLIENT_ID,
    clientSecret: process.env.HUBSPOT_CLIENT_SECRET,
    redirectUri: process.env.HUBSPOT_REDIRECT_URI ||
        'https://api.workflowguard.pro/api/auth/hubspot/callback',
    frontendUrl: process.env.FRONTEND_URL || 'https://www.workflowguard.pro',
    apiUrl: process.env.API_URL || 'https://api.workflowguard.pro',
    scopes: ['automation', 'oauth'].join(' '),
    apiBaseUrl: 'https://api.hubapi.com',
    apiTimeout: 30000,
    maxRetries: 3,
    retryDelay: 1000,
    rateLimitPerMinute: 100,
    rateLimitPerHour: 1000,
    rateLimitPerDay: 10000,
    tokenRefreshBuffer: 5 * 60 * 1000,
    maxTokenAge: 24 * 60 * 60 * 1000,
    maxWorkflowsPerRequest: 100,
    workflowSyncInterval: 5 * 60 * 1000,
    workflowBackupInterval: 24 * 60 * 60 * 1000,
    maxConsecutiveFailures: 5,
    failureBackoffMultiplier: 2,
    maxBackoffDelay: 60 * 1000,
    logLevel: process.env.HUBSPOT_LOG_LEVEL || 'info',
    enableDetailedLogging: process.env.HUBSPOT_DETAILED_LOGGING === 'true',
    tokenEncryptionKey: process.env.HUBSPOT_TOKEN_ENCRYPTION_KEY,
    enableTokenEncryption: process.env.HUBSPOT_ENCRYPT_TOKENS === 'true',
    enableHealthChecks: true,
    healthCheckInterval: 5 * 60 * 1000,
    connectionTimeout: 10 * 1000,
    webhookSecret: process.env.HUBSPOT_WEBHOOK_SECRET,
    webhookTimeout: 30 * 1000,
    minimumPortalPlan: 'professional',
    requiredFeatures: ['automation', 'workflows', 'api_access'],
    maxWorkflowVersions: 1000,
    workflowVersionRetentionDays: 365,
    auditLogRetentionDays: 730,
    enableAutomaticBackups: true,
    backupSchedule: '0 */6 * * *',
    backupRetentionDays: 30,
    enableFailureNotifications: true,
    notificationChannels: ['email', 'webhook'],
    criticalErrorThreshold: 3,
    enableCaching: true,
    cacheTTL: 5 * 60 * 1000,
    maxConcurrentRequests: 10,
    enableMockMode: process.env.HUBSPOT_MOCK_MODE === 'true',
    mockDataPath: process.env.HUBSPOT_MOCK_DATA_PATH,
    enableDataEncryption: true,
    enableAuditLogging: true,
    gdprCompliant: true,
    dataRetentionPolicy: 'standard',
    maxUsersPerPortal: 100,
    maxWorkflowsPerUser: 1000,
    maxApiCallsPerMinute: 100,
    maxApiCallsPerHour: 1000,
    enableAutomaticRetry: true,
    maxRetryAttempts: 3,
    retryStrategy: 'exponential_backoff',
    alertThresholds: {
        apiErrorRate: 0.05,
        responseTime: 5000,
        tokenRefreshFailures: 3,
        connectionFailures: 5,
    },
    features: {
        enableWorkflowComparison: true,
        enableVersionHistory: true,
        enableAutomaticBackups: true,
        enableRealTimeSync: true,
        enableAdvancedAnalytics: true,
        enableAuditLogging: true,
        enableApiAccess: true,
    },
}));
//# sourceMappingURL=hubspot.config.js.map